language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
os:
- linux
before_install:
- ./.travis/start-aerospike.sh
install:
- sudo apt-get install autoconf libssl-dev liblua5.1-dev
script:
- cd src/aerospike
- ./build.sh
- ../../.travis/load-extension.sh
- make test TESTS=tests/phpt
after_failure:
- cat configure.in
- cat Makefile
after_script:
- ./scripts/test-cleanup.sh
- cd ../..
notifications:
  slack:
    secure: tDCFds8n08P67Bz5RtkKv7OZBOW6xOa5dmSgcj27/JtEVNDOlyqYWyUCzYA/yJDXGCmefWx1iH9H5s6JtwvMurHuwHDeFp9TCjGwomCx1SZ/I9G31gX2h09Divhz9/C6CvsJGhbP1IPEy1xovC7JWuJHG2BfPgv1XtVGE5ozfUg=
